---
- name: Include variable overrides
  ansible.builtin.set_fact:
    _{{ cookiecutter.role_name | replace('-', '_') }}_package: "{{ '{{' }} {{ cookiecutter.role_name | replace('-', '_') }}_package | default(_{{ cookiecutter.role_name | replace('-', '_') }}_package_default | sorted_get(overrides)) {{ '}}' }}"
{%- raw %}
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
{%- endraw %}
  tags:
    - always

- name: Install {{ cookiecutter.role_name }} package
  ansible.builtin.package:
    name: "{{ '{{' }} _{{ cookiecutter.role_name | replace('-', '_') }}_package {{ '}}' }}"
    state: "{{ '{{' }} {{ cookiecutter.role_name | replace('-', '_') }}_state {{ '}}' }}"
  become: yes
