---
- name: Include variable overrides
  set_fact:
    _{{ cookiecutter.role_name | replace('-', '_') }}_package: "{{ '{{' }} {{ cookiecutter.role_name | replace('-', '_') }}_package | default(_default | sorted_get(overrides)) {{ '}}' }}"
  vars:
    _default: "_{{ '{{' }} {{ cookiecutter.role_name | replace('-', '_') }}_package_default {{ '}}' }}"
{%- raw %}
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
{%- endraw %}
  tags:
    - always

- name: Install {{ cookiecutter.role_name }} package
  become: yes
  package:
    name: "{{ '{{' }} _{{ cookiecutter.role_name | replace('-', '_') }}_package {{ '}}' }}"
    state: "{{ '{{' }} {{ cookiecutter.role_name | replace('-', '_') }}_state {{ '}}' }}"
