---
name: Molecule

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

jobs:

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@v2

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: run Pytest
        run: poetry run pytest -s
        env:
          PY_COLORS: '1'
