---
name: molecule

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

jobs:

  molecule:
    name: molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Run Pytest
        run: make test
        env:
          PY_COLORS: '1'
