---
name: molecule

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Generate devbox locale
        run: sudo locale-gen C.UTF-8

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Run Pytest
        run: devbox run -- make test
